import { asc, eq } from "drizzle-orm";
import { ensureDatabase, getDb, getRawDb } from "../../../db";
import { comments, itemTags, tags } from "../../../db/schema";

function clean(value: unknown, max: number) { return typeof value === "string" ? value.trim().slice(0, max) : ""; }
function actor(value: unknown) { const raw = value as Record<string, unknown> | null; if (!raw) return null; const result = { name: clean(raw.name, 80), team: clean(raw.team, 80), deviceId: clean(raw.deviceId, 100) }; return result.name && result.team && result.deviceId ? result : null; }
function fail(error: string, status = 400) { return Response.json({ error }, { status }); }
export async function GET(request: Request) { try { await ensureDatabase(); const query = new URL(request.url).searchParams; const itemId = clean(query.get("itemId"), 100); const db = getDb(); if (itemId) return Response.json({ tags: await db.select({ id: tags.id, name: tags.name, color: tags.color }).from(itemTags).innerJoin(tags, eq(itemTags.tagId, tags.id)).where(eq(itemTags.itemId, itemId)), comments: await db.select().from(comments).where(eq(comments.itemId, itemId)).orderBy(asc(comments.createdAt)) }); return Response.json({ tags: await db.select().from(tags).orderBy(asc(tags.name)) }); } catch (reason) { console.error(reason); return fail("เปิดข้อมูลการทำงานร่วมกันไม่สำเร็จ", 500); } }
export async function POST(request: Request) { try { await ensureDatabase(); const payload = await request.json() as Record<string, unknown>; const who = actor(payload.actor); const action = clean(payload.action, 30); if (!who) return fail("กรุณาระบุชื่อและทีมก่อนบันทึก"); const now = new Date().toISOString(); const db = getDb(); if (action === "create_tag") { const name = clean(payload.name, 40); if (!name) return fail("ชื่อแท็กห้ามว่าง"); const [tag] = await db.insert(tags).values({ id: crypto.randomUUID(), name, color: clean(payload.color, 20) || "neutral", createdByName: who.name, createdByTeam: who.team, createdAt: now }).returning(); return Response.json({ tag }, { status: 201 }); } if (action === "set_tags") { const itemId = clean(payload.itemId, 100); const ids = Array.isArray(payload.tagIds) ? payload.tagIds.map((id) => clean(id, 100)).filter(Boolean).slice(0, 12) : []; if (!itemId) return fail("ไม่พบรายการ"); const d1 = getRawDb(); await d1.prepare("DELETE FROM item_tags WHERE item_id = ?").bind(itemId).run(); if (ids.length) await d1.batch(ids.map((tagId) => d1.prepare("INSERT OR IGNORE INTO item_tags (item_id, tag_id, created_at) VALUES (?, ?, ?)").bind(itemId, tagId, now))); return Response.json({ ok: true }); } if (action === "comment") { const itemId = clean(payload.itemId, 100); const body = clean(payload.body, 2000); if (!itemId || !body) return fail("กรุณากรอกความคิดเห็น"); const [comment] = await db.insert(comments).values({ id: crypto.randomUUID(), itemId, body, authorName: who.name, authorTeam: who.team, createdAt: now }).returning(); return Response.json({ comment }, { status: 201 }); } return fail("คำสั่งไม่ถูกต้อง"); } catch (reason) { console.error(reason); return fail("บันทึกข้อมูลการทำงานร่วมกันไม่สำเร็จ", 500); } }
